### ISSUE TITLE
The Error 

### ISSUE THREAD

**Issue by SODANIKS** [rudynakodach/WebhookIntegrations#2]
When someone exit,login in and other im see the red error and no webhook(
![image](https://user-images.githubusercontent.com/61115286/217636955-459f6cac-e562-4a8e-905a-f544e69d1788.png)

**Comment by rudynakodach** [comment]
Hello.
I'm sorry I couldn't respond faster.
It looks like I did something wrong and a part of the AdventureAPI is missing. Is the issue still active? There have been many updates since verstion v1.10.1 and you should update the plugin as quickly as possible. Try updating and if anything goes wrong, tell me!

**Comment by rudynakodach** [comment]
I just read the error message again. It looks like you're using 1.12.2 as your server version. The plugin works only from 1.16 up to 1.19.3.

Updating WebhookIntegrations to 1.12.2 was planned and will be done soon. _I really mean it._

**Comment by rudynakodach** [comment]
Update and you're good to go. 1.12.2 is now supported and working! :)
