### ISSUE TITLE
Error loading plugin: Directory 'plugins\WebhookIntegrations-2.2.jar' failed to load!

### ISSUE THREAD

**Issue by coolshing** [rudynakodach/WebhookIntegrations#5]
This is my server log. It appears  some error on the top of log
how to solve it?
[latest.log](https://github.com/rudynakodach/WebhookIntegrations/files/10890830/latest.log)

**Comment by rudynakodach** [comment]
Hello.
It looks like auto-update failed. In your plugins folder there should be a file named `WebhookIntegrations-2.4.jar` in the directory `plugins\update\WebhookIntegrations-2.4.jar`. If you want to update, copy the file over and remove the `plugins/WebhookIntegrations` folder or remove the file in the `update` folder and set `auto-update` to `false` in the config to not update to the latest version. 

Keep in mind that this issue is NOT valid.
I didnt get enough information to recreate the bug, you didnt tell me what version and server software you were using. Luckily I was able to find the cause.

If you would have any more issues with the plugin, feel free to ask!
[EDIT: I didnt notice you've closed the issue]

**Comment by coolshing** [comment]
ok, I will try to set auto-update to false. If the plugin can't work, I will tell you.
Sorry about it, I forgot to proving the server information ( server version is purpur-1.19.3-1926, Minecraft version is 1.19.3)

**Comment by coolshing** [comment]
Hi, excuse me! I tried to set  auto-update to false, and I found the plugin didn't work either. But if I changed server core to spigot or bukkit, it can work.

**Comment by rudynakodach** [comment]
There's not enough information for me to start working on fixing this issue. If you are having a problem with the plugin, don't reopen an existing issue and just create a new one. Please open a new issue and provide all required info.
