### ISSUE TITLE
Missing server start/stop feature?

### ISSUE THREAD

**Issue by jkreider737** [rudynakodach/WebhookIntegrations#6]
According to the bukkit page and the README here, this plugin supports messages on server start/stop.
The config here: https://github.com/rudynakodach/WebhookIntegrations/blob/master/src/main/resources/config.yml#L27-L72
seems to suggest the same.
I get no plugin warnings when loading the server and the other messages send fine, but these don't seem to work.
There also doesn't seem to be any place in the Events folder where these webhook messages would be generated (https://github.com/rudynakodach/WebhookIntegrations/tree/master/src/main/java/rudynakodach/github/io/webhookintegrations/Events), and the only reference I could find for the feature flags was here: https://github.com/rudynakodach/WebhookIntegrations/blob/master/src/main/java/rudynakodach/github/io/webhookintegrations/Commands/WIActions.java#L78-L79
Do you plan on implementing these in the future? Thanks!
If you don't have time, I wouldn't mind putting up a PR to add them. Love the simplicity and features of this plugin.

**Comment by rudynakodach** [comment]
Hello. 
Since of the support of 1.12.2 the plugin no longer works as I really wanted.
 I am going to update the plugin back to 1.19. From now on I will be using the latest API versions because of what *freedom* it provides. You can expect the server start/stop messages being functional again in the next update which I will release soon!
 
 If your server is not using the latest minecraft vesions, consider using `ViaRewind`, `ViaBackwards`  or `ViaVersion` plugins to allow clients of newer/older version to join.
 
 I also wanted to apologise for you waiting so long. I will start working on fixing the plugin as fast as I can!

**Comment by rudynakodach** [comment]
As promised, server start/stop messages are back. If you are going to experience any other issues, please make a new issue.

**Comment by jkreider737** [comment]
That was fast! Thank you for your work!
